function results = preprocessing(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------

%%GOAL SIZE: 
goalx = 120;
goaly = 120;
xdif = max(goalx - size(im, 1), 0);
ydif = max(goaly - size(im, 2), 0);
%omg functions. fastest option
im = padarray(im, [xdif, ydif], 200, 'both');
im = imresize(im,[goalx goaly]);
% [p3, p4] = size(im);
% q1 = 50; 
% i3_start = floor((p3-q1)/2); % or round instead of floor; using neither gives warning
% i3_stop = i3_start + q1;
% 
% i4_start = floor((p4-q1)/2);
% i4_stop = i4_start + q1;
% 
% im = im(i3_start:i3_stop, i4_start:i4_stop, :);
% 
if(size(im,3)==3)
    % Convert RGB to grayscale, just in case. 
    imgray = rgb2gray(im);
else
    imgray = im;
end



results.imgray = imgray;


%--------------------------------------------------------------------------
